version: "3"
services: 
  nginx_reverse_proxy: 
    image: nginx:latest
    network_mode: host
    restart: always
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf